#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob globstar

# activate conda env
eval "$(conda shell.bash hook)"
conda activate dmvae
echo "CONDA_PREFIX: $CONDA_PREFIX"

# add parent directory to PYTHONPATH
parentdir="$(dirname "$PWD")"
export PYTHONPATH="$PYTHONPATH:$parentdir"
echo "PYTHONPATH: $PYTHONPATH"

ipython main.py -- \
  --data_dir="./MMMNIST/MNIST"                                                \
  --log_dir="runs/tmp"                                                        \
  --log-dir-versioning                                                        \
  --likelihood_str="laplace"                                                  \
  --num_modalities 5                                                          \
  --end_epoch 300                                                             \
  --batch_size 1024                                                           \
  --start_annealing 0                                                         \
  --annealing_epochs 50                                                       \
  --initial_learning_rate 0.001                                               \
  --reconstruction_coefs 1.                                                   \
  --llik_scale_param 0.1                                                      \
  --cm_dropout                                                                \
  --noisy_inputs                                                              \
  --num_workers 2                                                             \
  --num_imp_samples 1000                                                      \
  --eval_freq_generation 50                                                   \
  --eval_freq_likelihood 50                                                   \
  --eval_freq_fid 99999                                                       \
  \
  --class_dim 10  --style_dim 10                                              \
  --beta_prior_styles 10.                                                     \
  --beta_prior_content 0.                                                     \
  --beta_condreg 0.                                                           \
  --infomax_coef 100.0                                                        \
  --disentanglement_coefs 100.                                                \
  \
  --disentangle_style_only                                                    \
  --disjoint_partition                                                        \
  --freeze_content                                                            \
  --contrast_full_vs_subset                                                   \
  --reparam_c_before_infomax                                                  \
  # --random_seed 42                                                          \


# NOTE: infomax_coef is gamma, beta_prior_styles are betas, and  
# disentanglement_coefs are deltas

# NOTE: two minor differences to our paper: 
# (1) beta=10 instead of beta=100
# (2) learning_rate=0.001 instead of learning_rate=0.003
